name: admob_flutter
description: Admob plugin that shows banner ads using native platform views.
version: 4.0.0
homepage: https://github.com/kmcgill88/admob_flutter

environment:
    sdk: ">=3.0.0 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    lints: 3.0.0

flutter:
    plugin:
        platforms:
            android:
                package: com.shatsy.admobflutter
                pluginClass: AdmobFlutterPlugin
            ios:
                pluginClass: AdmobFlutterPlugin
